---
abstract: 'Release tests for minimum required versions'
author:
  - 'Mike Doherty <doherty@cpan.org>'
  - 'Marcel Grünauer <marcel@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Moose::Autobox: 0
  Test::DZil: 0
  Test::More: 0.96
  Test::Output: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-MinimumVersion
no_index:
  directory:
    - corpus
    - inc
    - examples
requires:
  Dist::Zilla: 4
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Test::MinimumVersion: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-Plugin-Test-MinimumVersion/issues
  homepage: http://metacpan.org/release/Dist-Zilla-Plugin-Test-MinimumVersion/
  repository: git://github.com/doherty/Dist-Zilla-Plugin-Test-MinimumVersion.git
version: 2.000005
